### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by seirerman** [webit-de/typo3-shortcut_statuscodes#1]
I got a php error after installing the extension:

> PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/typo3conf/ext/shortcut_statuscodes/Classes/Controller/ShortcutStatuscodesTypoScriptFrontendController.php on line 27

**Comment by seirerman** [comment]
This is because it ::class requires PHP 5.5, which TYPO3 6.2 doesn't (PHP 5.3.7+).

**Comment by seirerman** [comment]
This should work:
```
// $cObj = GeneralUtility::makeInstance(ContentObjectRenderer::class);
$cObj = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer');
```

**Comment by pixelbrackets** [comment]
Hey @seirerman Thanks for the report. Please use version 1.0.1 of the extension, now available in TER.

I have also just send version 2.0.0 to the TYPO3 repository, which drops support for PHP < 5.5.0.
