### ISSUE TITLE
Compatibility for TYPO3 10 LTS

### ISSUE THREAD

**Issue by webit-dev** [webit-de/typo3-shortcut_statuscodes#10]
Make the extension compatible with TYPO3 version 10.

**Comment by webit-dev** [comment]
PRs welcome.

**Comment by pixelbrackets** [comment]
Fixed in development, thanks to @christian-fries

We should fix #12 and #13 asap to push a new release.

**Comment by pixelbrackets** [comment]
Although #13 beeing a major bug, it is no blocker to release a new version. → https://packagist.org/packages/webit-de/shortcut_statuscodes#6.0.0
