### ISSUE TITLE
Bug: Middleware does not support different status codes anymore

### ISSUE THREAD

**Issue by pixelbrackets** [webit-de/typo3-shortcut_statuscodes#13]
*What did I do?*

- Install the extension in TYPO3 8, 9 and 10
- Create page A with shortcut mode "selected page"
- Create page B with shortcut mode "random subpage of selected/current page"

*What did I expect?*

- HTTP code 301 for page A
- HTTP code 307 for page B

*What happend instead?*

- In TYPO3 8 (xclass) everything working as expected
- in TYPO3 9 & 10 (middleware) page B emits code 301 as well

**Comment by pixelbrackets** [comment]
I stumbled upon this bug during the #11 review and it looks like the current middleware implementation is faulty.

The [original middleware class](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php) in the core has a Frontend Controller which allows to read fields from the shortcut page.

This way we would check `(int)$this->controller->page['shortcut_mode']` against `TYPO3\CMS\Core\Domain\Repository\PageRepository::SHORTCUT_MODE_NONE` and everything works.

But the current implementation [extends](https://github.com/webit-de/typo3-shortcut_statuscodes/blob/master/Classes/Middleware/ShortcutAndMountPointRedirect.php#L28) the core middleware, which hiddes the frontend controller in a [private argument](https://github.com/TYPO3/TYPO3.CMS/blob/10.4/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php#L40). So we can nit access the page properties.

Is there another way to access page properties in the middleware? Or could we overwrite the core middleware instead of extending it?
Or could the shortcut be manged somewhere else as well?

**Help and PRs welcome.**

**Comment by christian-fries** [comment]
Actually the custom middleware does not need to inherit from the core middleware, we could simply create our own middleware and add it to the stack before the core middleware.

In the custom middleware, we inject the `TypoScriptFrontendController` in order to be able to check against `(int)$this->controller->originalShortcutPage['shortcut_mode']`. 

I'll create a PR.

**Comment by pixelbrackets** [comment]
Ah, of course.

Thank you very much for the PR :tada: :100: :100: 

Tested, merged and released → [6.0.1](https://packagist.org/packages/webit-de/shortcut_statuscodes#6.0.1)
