### ISSUE TITLE
Error in database analyser

### ISSUE THREAD

**Issue by ste101** [webit-de/typo3-shortcut_statuscodes#3]
Hello,
the database analyser shows this error:

>`ALTER TABLE pages CHANGE tx_shortcutstatuscodes_language tx_shortcutstatuscodes_language int(11) NOT NULL default -1; 
>Current value: int(11) NOT NULL default '-1'`

**Comment by pixelbrackets** [comment]
Ah, I see. The field is created correctly in the database, but the database analyser needs a different format.

**Comment by pixelbrackets** [comment]
Fixed in version 2.1.1, should be available via TEr in a couple of minutes. Thanks for the report :)
