### ISSUE TITLE
Add compatibility for TYPO3 8 LTS

### ISSUE THREAD

**Issue by FlorianWessels** [webit-de/typo3-shortcut_statuscodes#4]
Raising dependencies in ext_emconf.php should be enough. The code looks quite good.

**Comment by pixelbrackets** [comment]
Hey Florian, thanks for the report :) Could you test this and send a PR?

**Comment by pixelbrackets** [comment]
Had a some spare time by accident and was able to test this right away → just published version 2.2.0 with compatibility for TYPO3 8 LTS. Have fun using it and please feel free to report any issues with it.
