### ISSUE TITLE
Compatibility for TYPO3 9.5 LTS

### ISSUE THREAD

**Issue by kurtwithslc** [webit-de/typo3-shortcut_statuscodes#6]
in Typo3 9.5 the extension does nothing.
"Extension scan" says: calculateLinkVars() is deprecated, it needs now an argument ...

**Comment by pixelbrackets** [comment]
Hey, it's on our bucket list. Would be awesome if you could send a Pull Request.

**Comment by pixelbrackets** [comment]
Merged into master branch, released version 4.2.0 just now: https://packagist.org/packages/webit-de/shortcut_statuscodes#4.2.0
