### ISSUE TITLE
raise PHP version restriction to include 7.4

### ISSUE THREAD

**Issue by maddy2101** [webit-de/typo3-shortcut_statuscodes#9]
Hello dear maintainer,

I try to use your extension in a TYPO3 v9 instance with PHP 7.4, but your latest version 5.0.0 allows only PHP until 7.2.99 in ext_emconf.php. Would you mind to raise the restriction and tag a new version?

Thanks for your consideration
Anja

**Comment by pixelbrackets** [comment]
Here we go :tada: https://packagist.org/packages/webit-de/shortcut_statuscodes#5.1.0
